### ISSUE TITLE
Feat/2 entity 수정

### ISSUE THREAD

**Issue by kangyunsik** [Kreamish/KreamishServer#5]
Feat/2 #3 

수정 사항

**1. Entity key 생성 전략 Auto -> Identity 변경 필요**

 - Auto의 경우, 적합한 전략을 자동으로 선택한다고 합니다.
 - PK가 auto-increment인 Item Table의 경우 MySQL 기준 Item_seq 라는 시퀀스를 조회하려고 시도하는 문제가 있습니다.
 - Identity 로 변경하면 문제가 없는데, Auto로 두되 다른 방법이 있다면, 얘기 나눠보면 좋겠습니다

**2. 오타 수정 base_entitiy.updateid -> update_id, item.model_dode -> model_code**

 - column name 에 오타가 있습니다

**3. Item entity' IMAGE_URL 멤버 변수 추가**

 - imageUrl 멤버 변수 추가해야 될 것 같습니다.
 - 테이블 설계도에 IMAGE_URL 필드가 누락 되어 있어서 컨플에 추가 후 업로드 하겠습니다.

**Comment by seung-woo-ryu** [comment]
### ToDo
- [x] Entity key 생성 전략 Auto -> Identity 변경 필요
- [x] 오타 수정 base_entitiy.updateid -> update_id, item.model_dode -> model_code
- [x] �Item entity' IMAGE_URL �멤버 변수 추가
